# Generated by Django 3.2 on 2021-09-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='auctions.Listing'),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
