# Generated by Django 3.2 on 2021-09-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210914_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
