# Generated by Django 3.2 on 2021-09-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210916_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
