# Generated by Django 3.2 on 2021-09-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_bid_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.FloatField(default=0.0),
        ),
    ]
