# Generated by Django 3.2 on 2021-09-16 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_current_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='current_winner',
        ),
    ]
